[scene]

[[scene.ref]]
id = "body"
model = { src = "ambulance.glb", mesh = [
    { name = "Mesh body", rename = "body" },
    { name = "Mesh doorLeft", rename = "door_left" },
    { name = "Mesh doorRight", rename = "door_right" },
] }

[[scene.ref]]
id = "wheel"
model = "wheel_truck.toml"

[[scene.ref]]
id = "front_left"
position = [1, 0, 1]

[[scene.ref]]
id = "back_left"
position = [1, 0, -1]
