[scene]

[[scene.ref]]
id = "body"
model = { src = "police.glb", mesh = [
    { name = "Mesh body" },
    { name = "Mesh grill" },
] }

[[scene.ref]]
id = "wheel"
model = "wheel_dark.glb"

[[scene.ref]]
id = "front_left"
position = [1, 0, 1]

[[scene.ref]]
id = "back_left"
position = [1, 0, -1]
