[scene]

[[scene.ref]]
id = "body"
model = "race.glb"

[[scene.ref]]
id = "wheel"
model = "wheelRacing.glb"

[[scene.ref]]
id = "front_left"
position = [1, 0, 1]

[[scene.ref]]
id = "back_left"
position = [1, 0, -1]