[package]
name = "screen-13"
version = "0.2.0"
authors = ["John Wells <john@attackgoat.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/attackgoat/screen-13"
homepage = "https://github.com/attackgoat/screen-13"
documentation = "https://docs.rs/screen-13"
keywords = ["gamedev", "vulkan"]
categories = ["game-development", "multimedia::images", "rendering::engine"]
description = "An easy-to-use 2D/3D rendering engine in the spirit of QBasic."

# 🦀📦: Feature Set: https://github.com/attackgoat/screen-13#optional-features
[features]
default = [
    "debug",
    "event-loop",
    "pak",
]
bake = ["glob", "pak"]
debug = []
event-loop = [] #TODO!!!!!! OPTIONALS HERE!~
pak = [] #TODO!!!!!! OPTIONALS HERE!~

[dependencies]
arrayvec = "0.7"
ash = "0.35"
ash-window = "0.9"
bincode = "1.3"
bitflags = "1.3"
brotli = "3.3"
byteorder = "1.4"
derive_builder = "0.10"
glam = { version="0.20", features=["serde"] }
glob = { version="0.3.0", optional=true }
gltf = "1.0"
gpu-allocator = "0.16"
image = "0.23"
imgui = { version = "0.8", optional = true }
itertools = "0.10"
log = "0.4"
num-format = "0.4.0"
num-traits = "0.2"
ordered-float = { version = "2.0", features=["serde"] }
parking_lot = "0.12"
paste = "1.0"
puffin = "0.12"
raw-window-handle = "0.4"
serde = { version="1.0", features=["derive"] }
serde_bytes = "0.11"
snap = "1.0"
spirv-reflect = "0.2"
toml = "0.5"
typenum = "1.12"
vk-sync = { version = "0.3.0", package="vk-sync-fork" } # // HACK: https://github.com/gwihlidal/vk-sync-rs/pull/4 -> https://github.com/expenses/vk-sync-rs
winit = { version="0.26" }

# TODO: https://github.com/orium/archery/pull/5 waiting on release
archery = { git="https://github.com/orium/archery" }

# TODO: https://github.com/attackgoat/bmfont-rust/tree/iter-char waiting on PR+merge+release
bmfont = { git="https://github.com/attackgoat/bmfont-rust", branch="iter_char", default-features=false, features=["serde"] }

# 🦀📦: Build Stuff
[build-dependencies]
genmesh = "0.6"
glam = "0.20"
lazy_static = "1.4"

[dev-dependencies]
anyhow = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
screen-13-fx = { path = "contrib/screen-13-fx" }

# Always compile the `image` dependency in release mode; it is slow with debug assertions turned on
[profile.dev.package.image]
opt-level = 3

[package.metadata.docs.rs]
all-features = true