[package]
name = "screen-13"
version = "0.1.0"
authors = ["john wells <john@attackgoat.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/attackgoat/screen-13"
homepage = "https://github.com/attackgoat/screen-13"
documentation = "https://docs.rs/screen-13"
keywords = ["gamedev" ]
categories = ["game-engines"]
description = """
An easy-to-use 3D game engine in the spirit of QBasic.
"""

[dependencies]
app_dirs = "1.2"
bincode = "1.3"
bmfont = "0.3"
brotli = "3.3"
byteorder = "1.3"
gfx-hal = "0.6"
glam = { version = "0.11", features = ["serde"] }
image = "0.23"
serde = { version = "1.0", features = ["derive"] }
snap = "1.0"
toml = "0.5"
typenum = "1.12"
winit = { version = "0.23", features = ["web-sys"] }

# Debug deps below: https://github.com/rust-lang/cargo/issues/7634
log = "0.4"
num-format = "0.4.0"
pretty_env_logger = "0.4"

# TODO: Baking deps here https://github.com/rust-lang/cargo/issues/1982 maybe use features and [[bin]] required features?
gltf = "0.15"
sha1 = "0.6"
shaderc = "0.7"

[build-dependencies]
genmesh = "0.6"
lazy_static = "1.4"
shaderc = "0.7"

[dev-dependencies]
rand = "0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
console_log = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies.gfx-backend-gl]
version = "0.6"

# [target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
# version = "0.3"
# features = ["console", "Document", "Element", "HtmlElement", "Node", "Window"]

[target.'cfg(any(target_os = "freebsd", target_os = "dragonfly", target_os = "linux", target_os = "netbsd", target_os = "openbsd"))'.dependencies]
gfx-impl = { version = "0.6", features = ["x11"], package = "gfx-backend-vulkan" }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
gfx-impl = { version = "0.6", package = "gfx-backend-metal" }

[target.'cfg(target_os = "windows")'.dependencies]
gfx-impl = { version = "0.6", package = "gfx-backend-dx11" }
