[package]
name = "screen-13"
version = "0.3.0"
authors = ["John Wells <john@attackgoat.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/attackgoat/screen-13"
homepage = "https://github.com/attackgoat/screen-13"
documentation = "https://docs.rs/screen-13"
keywords = ["gamedev", "vulkan"]
categories = ["game-development", "multimedia::images", "rendering::engine"]
description = "An easy-to-use Vulkan rendering engine in the spirit of QBasic."

[dependencies]
archery = { version = "0.4.3", package = "a_r_c_h_e_r_y" } # HACK: Waiting on main pkg to release
ash = "0.37"
ash-window = "0.10"
bitflags = "1.3"
derive_builder = "0.11"
gpu-allocator = { git = "https://github.com/Traverse-Research/gpu-allocator.git", branch = "ash-0.37" } # https://github.com/Traverse-Research/gpu-allocator/pull/104
log = "0.4"
ordered-float = "2.0"
parking_lot = "0.12"
paste = "1.0"
puffin = "0.13"
raw-window-handle = "0.4"
spirq = "0.5"
vk-sync = { version = "0.4.0", package = "vk-sync-fork" }  # // HACK: https://github.com/gwihlidal/vk-sync-rs/pull/4 -> https://github.com/expenses/vk-sync-rs
winit = { version = "0.26" }

[target.'cfg(target_os = "macos")'.dependencies]
ash-molten = "0.12"

[dev-dependencies]
anyhow = "1.0"
bmfont = { version = "0.3", default-features = false }
glam = "0.20"
image = "0.24"
inline-spirv = "0.1"
log = "0.4"
polyhedron-ops = "0.2"
pretty_env_logger = "0.4"
rand = "0.8"
screen-13-fx = { path = "contrib/screen-13-fx" }
screen-13-imgui = { path = "contrib/screen-13-imgui" }

