[package]
name = "screen-13-imgui"
version = "0.1.0"
authors = ["John Wells <john@attackgoat.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
bytemuck = "1.13"

# HACK: https://github.com/imgui-rs/imgui-rs/pull/716
imgui = { git = "https://github.com/imgui-rs/imgui-rs", rev = "4d0c9ebc0faaea421e59e0a58f712abbb18c3093" } 
imgui-winit-support = { git = "https://github.com/imgui-rs/imgui-rs", rev = "4d0c9ebc0faaea421e59e0a58f712abbb18c3093" }

inline-spirv = "0.1"
screen-13 = { path = "../.." }
screen-13-fx = { path = "../screen-13-fx" }
