[content]
compression = "snap"

[[content.group]]
assets = [
    "gltf/car_kit/ambulance.toml",
    "gltf/car_kit/firetruck.toml",
    "gltf/car_kit/police.toml",
    "gltf/car_kit/race.toml",
    "scene/city.toml",
]
